org: jschuur
app: serverless-prisma-esm
service: serverless-prisma-esm
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-webpack-prisma

custom:
  webpack:
    includeModules: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  animals:
    handler: handler.animals
    events:
      - httpApi:
          path: /
          method: get
